FROM node:14.21.3-alpine3.17 as dev-deps
WORKDIR /app
COPY package.json package.json
RUN npm install

FROM node:14.21.3-alpine3.17 as builder
WORKDIR /app
COPY --from=dev-deps /app/node_modules ./node_modules
COPY . .
# RUN yarn test
RUN npm run build


FROM nginx:1.23.3 as prod
EXPOSE 80

COPY --from=builder /app/dist/frontend /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

CMD [ "nginx","-g","daemon off;"]

