version: "3.7"
services:
  app:
    build:
      args:
        user: www-data
        uid: 1000
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-php
    container_name: laravel-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
      - ./backend/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www
      - ./backend/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
      
  db:
    image: postgres
    container_name: laravel-db
    restart: unless-stopped
    volumes:
      - "./backend/postgres/backup:/backup/"
      - "./backend/postgres/data:/var/lib/postgresql/data:delegated"
    env_file:
      - backend/postgres/database.env # configure postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  frontend-app: 
    hostname: frontend-app
    container_name: frontend-app-angular
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '85:85' 
  
  vr360-app: 
    hostname: vr360-app
    container_name: vr360-app-react
    build: 
      context: ./vr360
      dockerfile: Dockerfile
    ports:
      - '86:86' 

networks:
  app-network:
    driver: bridge

